import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
    faArrowLeftLong,
    faChartColumn,
    faCheck,
    faChevronLeft,
    faChevronRight,
    faCircleCheck,
    faCog,
    faDashboard,
    faEye,
    faFile,
    faMagnifyingGlass,
    faPencil,
    faPeopleGroup,
    faPlusCircle,
    faRightFromBracket,
    fas,
    faCheckCircle,
    faXmarkCircle,
    faTable,
    faTrash,
    faXmark,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faArrowLeftLong,
    fas,
    faCheckCircle,
    faXmarkCircle,
    faDashboard,
    faChartColumn,
    faTable,
    faMagnifyingGlass,
    faPlusCircle,
    faFile,
    faXmark,
    faCog,
    faTrash,
    faPencil,
    faCheck,
    faRightFromBracket,
    faEye,
    faChevronLeft,
    faChevronRight,
    faCircleCheck,
    faPeopleGroup,
)

export { FontAwesomeIcon }